### PR TITLE
create one take-home challenge for all candidates - junior to staff engineer. make some parts simpler. leave room for more experienced engineers to show their skills.

### PR DESCRIPTION
**Pull request by grggls**

### CODE REVIEW

**Comment by lucenabruno** [comment]
- are we sharing this repo with the candidate?
- it could be explicit that we needs to create a pr
- we can also suggest using localstack for mockup aws. I was using it to run terraform plans for candidate(s).
- in "Create a Kubernetes cluster" do we want a script to bootstrap? should be explicit?
- what about a simple github workflow to plan terraform?

**Comment by grggls** [comment]
- we're sharing this repo with the candidate... but i'll add a 'fork and submit via your own github account' line to the beginning

- let's not complicate things with localstack or mockup aws

- I added this part. Let me know if it wasn't clear - "- Update [main.tf](./main.tf) and this README in the root directory. You may also need to update the providers that you find there. Make sure that the engineer reviewing your work has all the information they need to run your scripts, build your cluster, and repeat the setup you did."

- let's not complicate things with github workflow. there's plenty of ways to script and automate this, and I'd like to leave room for the candidates to use tools they're familiar with

**Review by lucenabruno — COMMENTED** [review]
lgtm

**Review by lucenabruno — APPROVED** [review]
lgtm

**Pull request merged**
